"""rename_tenant_to_organization

Revision ID: 03b80c6d6472
Revises: 46e9a700582f
Create Date: 2025-11-22 17:02:34.236608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03b80c6d6472'
down_revision: Union[str, Sequence[str], None] = '46e9a700582f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_column('users', 'tenant_id')
    op.add_column('workspaces', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('workspaces', sa.Column('created_by', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('workspaces_tenant_id_fkey'), 'workspaces', type_='foreignkey')
    op.drop_constraint(op.f('workspaces_create_by_fkey'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'workspaces', 'organizations', ['organization_id'], ['id'])
    op.drop_column('workspaces', 'tenant_id')
    op.drop_column('workspaces', 'create_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('create_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('workspaces_create_by_fkey'), 'workspaces', 'users', ['create_by'], ['id'])
    op.create_foreign_key(op.f('workspaces_tenant_id_fkey'), 'workspaces', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('workspaces', 'created_by')
    op.drop_column('workspaces', 'organization_id')
    op.add_column('users', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('users', 'organization_id')
    op.create_table('tenants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey'))
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
